Feature/274 release guide
exasol/release-droid pull request #276
Opened 2022-11-15 15:20 UTC by ckunki

fixes #274

2022-12-01 14:04 UTC, kaklakariada requested changes

2022-12-01 14:04 UTC, kaklakariada commented on src/main/resources/release-guide-template.html
> +		xfont-style: normal;
```suggestion
	font-size: 80%;
	color: #666;
	vertical-align: bottom;
	font-style: italic;
}

.error {
	color: #f00;
	font-style: italic;
}

code {
	background-color: #eeeeee;
	padding: 1px;
	xcolor: #055;
	xfont-style: normal;
```

2022-12-05 07:37 UTC, ckunki commented on doc/user_guide/user_guide.md
> +The lines with prefix "jira" are only relevant if releasing to platform Jira.
Yes, but the functionality is still implemented. I agreed to not removing it, yet.

2022-12-05 07:41 UTC, ckunki commented on src/main/java/com/exasol/releasedroid/adapter/repository/LocalRepositoryGate.java
> +        final String name = new RemoteName(Git.open(folder.toFile())).retrieve()
Ups - yes, thanks!

2022-12-05 07:47 UTC, ckunki reviewed
reviewed findings

2022-12-05 07:58 UTC, kaklakariada approved these changes

2022-12-05 09:55 UTC, kaklakariada approved these changes

2022-12-05 10:28 UTC, merged